### ISSUE TITLE
Update annoy version

### ISSUE THREAD

**Issue by paluh** [jimkang/annoy-node#3]
Hi,

Thanks for writing this library!

I want to use your bindings but AFAIU it contains two years old version of annoy and I need some recent feature (Manhatan . Are you interested in upgrading (we want to provide PR's)?

I'm not an node.js expert, but I wonder if we could move annoy code outside of this bindings (like downloading it during installation), so it will be clear which version we are building against and the update path would be somewhat easier (making diffs between annoy versions etc.). Do you think this is good idea?

**Comment by jimkang** [comment]
Hi – I am interested in upgrading and am open to PRs! Rather than downloading, however, I'd prefer an approach that uses [prebuilds](https://github.com/prebuild/prebuild) to avoid complexity and chances of failure.
