### ISSUE TITLE
Async support

### ISSUE THREAD

**Issue by moooji** [jimkang/annoy-node#6]
It looks like all methods are currently sync/blocking, which means that many concurrent search requests will have poor performance and block the event loop.

Have you thought about making the methods async?

I might try to create a PR for that, but I have little experience with the C++ add-on code. Do you maybe have any hints or background information that might help?

**Comment by jimkang** [comment]
Thanks for offering to give this a shot!

The thing is, the add-on code is [pretty thin](https://github.com/jimkang/annoy-node/blob/master/annoyindexwrapper.cc#L138). To make it support concurrency, you'd have to reach into the [core Annoy C++ code itself](https://github.com/spotify/annoy), which would basically mean forking from Annoy.

I don't want to do that, but here is a strategy you can use to support concurrency:

1) Create multiple Node processes, each with an Annoy index.
2) Have another Node process (or something like pm2 or maybe ha-proxy) route search requests to them.

This way, only when all of the processes are busy will there be any blocking. It's similar to the way UWSGI achieves concurrency - just balancing requests across child processes.

All that said, if you haven't already, I recommend you first test with a single instance to make sure that it's not fast enough. [Annoy can perform between 100 and 10,000 queries per second on a large AWS instance.](https://github.com/erikbern/ann-benchmarks#results) Depending on your traffic, it might be fine, while remaining simple.

**Comment by jimkang** [comment]
Now, that I see this again, I think it's more accurate to say that we wouldn't need to fork from Annoy, but we would have to put threading code in the add-on that would use a pool of indexes. Overall, I think it would be less failure-prone to do that kind of rotating through the pool at the process level using the strategy above.
