### ISSUE TITLE
node v12 error: too few arguments to function call, expected 2, have 1

### ISSUE THREAD

**Issue by loretoparisi** [jimkang/annoy-node#7]
This issue is related to packages `level`, `leveldown` and causes errors in `node v12.13.x` - see https://github.com/Level/leveldown/issues/695

**Comment by jimkang** [comment]
Thanks for reporting! I did bump up `level` (in a branch), there are still other problems with building on Node 10 and Node 12. I'm going to look into them; it may be that add-ons have changed in those versions of Node.

**Comment by jimkang** [comment]
@loretoparisi You should be able to `npm install --save annoy@latest` and have a version that works with Node 12.

**Comment by loretoparisi** [comment]
@jimkang thank you I will test and back here.
